header: Almer
title: Almer Colic
page_title: Almer Colic
baseurl: "" 
url: "" 

remote_theme: eliottvincent/bay

header:
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: Blog  
    - name: Impressum  

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: almer@acolic.de
      link: mailto:almer@acolic.de
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/almer-colic-62867b155
    - name: GitHub
      link: http://github.com/almercolic